# Artsdatabanken

In [18]:
import pandas as pd

In [19]:
url = "https://nortaxa.artsdatabanken.no/api/v1/DataTransfer/Export?scientificNameId=-1&includeSynonyms=true&includeVernacularNames=true&exportType=Csv"
biota =pd.read_csv(url, sep = ";", na_values = "NaN",dtype ="str")
#url = 'https://nortaxa.artsdatabanken.no/api/v1/DataTransfer/Export?scientificNameId=99480&includeSynonyms=true&includeVernacularNames=true&exportType=Csv'
#'blob:https://nortaxa.artsdatabanken.no/3f6d6c4f-5312-4d12-8624-a99c2272afb8'

In [20]:
display(biota)

,VernacularNameBokmaal,StatusBokmaal,ReferenceBokmaal,CommentBokmaal,ValidFromBokmaal,VernacularNameNynorsk,StatusNynorsk,ReferenceNynorsk,CommentNynorsk,ValidFromNynorsk,...,PresentationName,Rank,TaxonomicStatus,NomenclaturalStatuses,NameString,Author,Reference,ValidFrom,Comment,ExistsInNorway
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Biota,Sphere,Accepted,NaN,Biota,NaN,NaN,01.01.2008,Biota,False
1,dyreriket,Preferred,CatalogueOfLife2008rev,NaN,07.02.2012,dyreriket,Preferred,NaN,NaN,07.02.2012,...,Animalia,Kingdom,Accepted,NaN,Animalia,NaN,CatalogueOfLife2008rev,30.04.2009,"Importert fra ""Catalogue of Life""",False
2,erkebakterier,Preferred,NaN,NaN,02.02.2012,NaN,NaN,NaN,NaN,NaN,...,Archaea,Kingdom,Accepted,NaN,Archaea,NaN,CatalogueOfLife2008rev,30.04.2009,"Importert fra ""Catalogue of Life""",False
3,bakterier,Preferred,NaN,NaN,02.02.2012,NaN,NaN,NaN,NaN,NaN,...,Bacteria,Kingdom,Accepted,NaN,Bacteria,NaN,CatalogueOfLife2008rev,30.04.2009,"Importert fra ""Catalogue of Life""",False
4,det gule riket,Preferred,CatalogueOfLife2008rev,NaN,02.02.2012,det gule riket,Preferred,NaN,NaN,02.02.2012,...,Chromista,Kingdom,Accepted,NaN,Chromista,Caval.-Sm.,NaN,30.04.2009,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Moniliformida,Order,Accepted,NaN,Moniliformida,NaN,CatalogueOfLife2008rev,30.04.2009,"Importert fra ""Catalogue of Life""",False
226392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Oligacanthorhynchida,Order,Accepted,NaN,Oligacanthorhynchida,NaN,CatalogueOfLife2008rev,30.04.2009,"Importert fra ""Catalogue of Life""",False
226393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Oligacanthorhynchidae,Family,Accepted,NaN,Oligacanthorhynchidae,NaN,NaN,08.11.2012,NaN,False
226394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Macracanthorhynchus,Genus,Accepted,NaN,Macracanthorhynchus,NaN,NaN,08.11.2012,NaN,False
226395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Macracanthorhynchus hirudinaceus,Species,Accepted,NaN,hirudinaceus,"(Pallas, 1781)",NaN,28.01.2015,NaN,True

In [21]:
url = 'https://nortaxa.artsdatabanken.no/api/v1/DataTransfer/Export?scientificNameId=99480&includeSynonyms=true&includeVernacularNames=true&exportType=Csv'
#url = "https://nortaxa.artsdatabanken.no/api/v1/DataTransfer/Export?scientificNameId=-1&includeSynonyms=true&includeVernacularNames=true&exportType=Csv"
biota =pd.read_csv(url, sep = ";", na_values = "NaN",dtype ="str")
biota

,VernacularNameBokmaal,StatusBokmaal,ReferenceBokmaal,CommentBokmaal,ValidFromBokmaal,VernacularNameNynorsk,StatusNynorsk,ReferenceNynorsk,CommentNynorsk,ValidFromNynorsk,...,PresentationName,Rank,TaxonomicStatus,NomenclaturalStatuses,NameString,Author,Reference,ValidFrom,Comment,ExistsInNorway
0,orkidéfamilien,Preferred,NaN,NaN,13.09.2009,orkidéfamilien,Preferred,NaN,NaN,13.09.2009,...,Orchidaceae,Family,Accepted,NaN,Orchidaceae,Juss.,NaN,20.08.2009,NaN,False
1,narrmarihandslekta,Preferred,NaN,NaN,13.09.2009,narrmarihandslekta,Preferred,NaN,NaN,13.09.2009,...,Anacamptis,Genus,Accepted,NaN,Anacamptis,Rich.,NaN,20.08.2009,NaN,False
2,skogfrueslekta,Preferred,NaN,NaN,13.09.2009,skogfrueslekta,Preferred,NaN,NaN,13.09.2009,...,Cephalanthera,Genus,Accepted,NaN,Cephalanthera,Rich.,NaN,20.08.2009,NaN,False
3,fjellkurleslekta,Preferred,NaN,NaN,13.09.2009,fjellkurleslekta,Preferred,NaN,NaN,13.09.2009,...,Chamorchis,Genus,Accepted,NaN,Chamorchis,Rich.,NaN,20.08.2009,NaN,False
4,grønnkurleslekta,Preferred,NaN,NaN,13.09.2009,grønkurleslekta,Preferred,NaN,NaN,13.09.2009,...,Coeloglossum,Genus,Accepted,NaN,Coeloglossum,Hartm.,NaN,20.08.2009,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,stor skogfrue,Preferred,NaN,NaN,03.07.2018,stor skogfrue,Preferred,NaN,NaN,03.07.2018,...,Cephalanthera pallens,Species,Synonym,NaN,pallens,Rich.,NaN,25.06.2016,NaN,True
376,narrmarihand,Preferred,NaN,NaN,13.09.2009,narrmarihand,Preferred,NaN,NaN,13.09.2009,...,Anacamptis morio,Species,Accepted,NaN,morio,"(L.) R.M.Bateman, Pridgeon & M.W.Chase",NaN,24.06.2016,NaN,True
377,salepsrot,Preferred,NaN,NaN,03.07.2018,salepsrot,Preferred,NaN,NaN,03.07.2018,...,Anacamptis pyramidalis,Species,Accepted,NaN,pyramidalis,(L.) Rich.,NaN,24.06.2016,NaN,False
378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Anacamptis laxiflora,Species,Accepted,NaN,laxiflora,"(Lam.) R.M.Bateman, Pridgeon & M.W.Chase",NaN,12.04.2018,NaN,False
379,myrmarihand,Preferred,NaN,NaN,03.07.2018,myrmarihand,Preferred,NaN,NaN,03.07.2018,...,Anacamptis palustris,Species,Accepted,NaN,palustris,"(Jacq.) R.M.Bateman, Pridgeon & M.W.Chase",NaN,12.04.2018,NaN,False

In [22]:
#biota[pd.notna(biota['Species'])]
biota['Species']

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
          ...
375        pallens
376          morio
377    pyramidalis
378      laxiflora
379      palustris
Name: Species, Length: 380, dtype: object

## Nortaxa

In [23]:

import pandas as pd
artsnavnebase = "https://nortaxa.artsdatabanken.no/api/v1/DataTransfer/Export?scientificNameId=-1&includeSynonyms=true&includeVernacularNames=true&exportType=Csv"
artsnavnebase =pd.read_csv(artsnavnebase, sep = ";")
artsnavnebase.head

C:\Users\endofs\AppData\Local\Temp\ipykernel_36536\4147161154.py:3: DtypeWarning: Columns (7,8,12,19,20,22,23,24,26,27,28,30,31,33,34,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  artsnavnebase =pd.read_csv(artsnavnebase, sep = ";")

<bound method NDFrame.head of        VernacularNameBokmaal StatusBokmaal        ReferenceBokmaal  \
0                        NaN           NaN                     NaN
1                  dyreriket     Preferred  CatalogueOfLife2008rev
2              erkebakterier     Preferred                     NaN
3                  bakterier     Preferred                     NaN
4             det gule riket     Preferred  CatalogueOfLife2008rev
...                      ...           ...                     ...
226391                   NaN           NaN                     NaN
226392                   NaN           NaN                     NaN
226393                   NaN           NaN                     NaN
226394                   NaN           NaN                     NaN
226395                   NaN           NaN                     NaN

       CommentBokmaal ValidFromBokmaal VernacularNameNynorsk StatusNynorsk  \
0                 NaN              NaN                   NaN           NaN
1                 NaN       07.02.2012             dyreriket     Preferred
2                 NaN       02.02.2012                   NaN           NaN
3                 NaN       02.02.2012                   NaN           NaN
4                 NaN       02.02.2012        det gule riket     Preferred
...               ...              ...                   ...           ...
226391            NaN              NaN                   NaN           NaN
226392            NaN              NaN                   NaN           NaN
226393            NaN              NaN                   NaN           NaN
226394            NaN              NaN                   NaN           NaN
226395            NaN              NaN                   NaN           NaN

       ReferenceNynorsk CommentNynorsk ValidFromNynorsk  ...  \
0                   NaN            NaN              NaN  ...
1                   NaN            NaN       07.02.2012  ...
2                   NaN            NaN              NaN  ...
3                   NaN            NaN              NaN  ...
4                   NaN            NaN       02.02.2012  ...
...                 ...            ...              ...  ...
226391              NaN            NaN              NaN  ...
226392              NaN            NaN              NaN  ...
226393              NaN            NaN              NaN  ...
226394              NaN            NaN              NaN  ...
226395              NaN            NaN              NaN  ...

                        PresentationName     Rank TaxonomicStatus  \
0                                  Biota   Sphere        Accepted
1                               Animalia  Kingdom        Accepted
2                                Archaea  Kingdom        Accepted
3                               Bacteria  Kingdom        Accepted
4                              Chromista  Kingdom        Accepted
...                                  ...      ...             ...
226391                     Moniliformida    Order        Accepted
226392              Oligacanthorhynchida    Order        Accepted
226393             Oligacanthorhynchidae   Family        Accepted
226394               Macracanthorhynchus    Genus        Accepted
226395  Macracanthorhynchus hirudinaceus  Species        Accepted

        NomenclaturalStatuses             NameString          Author  \
0                         NaN                  Biota             NaN
1                         NaN               Animalia             NaN
2                         NaN                Archaea             NaN
3                         NaN               Bacteria             NaN
4                         NaN              Chromista      Caval.-Sm.
...                       ...                    ...             ...
226391                    NaN          Moniliformida             NaN
226392                    NaN   Oligacanthorhynchida             NaN
226393                    NaN  Oligacanthorhynchidae             NaN
226394                    NaN    Macracanthorhynchus             NaN
226395                    NaN           hirudinaceus  (Pallas, 1781)

                     Reference   ValidFrom                            Comment  \
0                          NaN  01.01.2008                              Biota
1       CatalogueOfLife2008rev  30.04.2009  Importert fra "Catalogue of Life"
2       CatalogueOfLife2008rev  30.04.2009  Importert fra "Catalogue of Life"
3       CatalogueOfLife2008rev  30.04.2009  Importert fra "Catalogue of Life"
4                          NaN  30.04.2009                                NaN
...                        ...         ...                                ...
226391  CatalogueOfLife2008rev  30.04.2009  Importert fra "Catalogue of Life"
226392  CatalogueOfLife2008rev  30.04.2009  Importert fra "Catalogue of Life"
226393                     NaN  08.11.2012                                NaN
226394                     NaN  08.11.2012                                NaN
226395                     NaN  28.01.2015                                NaN

       ExistsInNorway
0               False
1               False
2               False
3               False
4               False
...               ...
226391          False
226392          False
226393          False
226394          False
226395           True

[226396 rows x 53 columns]>

In [24]:
artsnavnebase.loc[artsnavnebase["NameString"]=="Pinophyta"][["VernacularNameBokmaal"]]

     VernacularNameBokmaal
1340   nakenfrøete planter

## Rødlista

In [100]:
url = "https://artsdatabanken.no/lister/rodlisteforarter/2021?Name=&SortBy=ScientificName&Meta=Visited&IsCheck=Area&IsCheck=Insekter&Export=true"
RL =pd.read_excel(url)
display(RL)

,Id for vurderingen,Vurderingsområde,Ekspertkomité,Artsgruppe,Taksonomisk sti,Vitenskapelig navn id,Vitenskapelig navn,Autor,Populærnavn,Taksonomisk nivå,...,Trøndelag,Nordland,Troms,Finnmark,Jan Mayen,Nordsjøen,Norskehavet,Barentshavet nord og Polhavet,Barentshavet sør,Grønlandshavet
0,15090,Norge,Karplanter,Karplanter,Plantae/Magnoliophyta/Monocots/Poales/Poaceae/...,153890,×Ammocalamagrostis baltica,(Flüggé ex Schrad.) P.Fourn.,østersjørør,Art,...,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent
1,15002,Svalbard,Karplanter,Karplanter,Plantae/Magnoliophyta/Monocots/Poales/Poaceae/...,153891,×Arctodupontia scleroclada,(Rupr.) Tzvelev,kongsfjordgras,Art,...,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent
2,2444,Svalbard,Karplanter,Karplanter,Plantae/Magnoliophyta/Monocots/Poales/Poaceae/...,153896,×Pucciphippsia vacillans,(Th.Fr.) Tzvelev,svalbardgras,Art,...,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent,ikke kjent
3,11455,Norge,Edderkoppdyr,Edderkoppdyr,Animalia/Arthropoda/Arachnida/Araneae/Linyphii...,2644,Abacoproeces saltuum,"(L. Koch, 1872)",klippeedderkopp,Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,27083,Norge,Biller,Biller,Animalia/Arthropoda/Insecta/Coleoptera/Carabid...,5565,Abax parallelepipedus,"(Piller & Mitterpacher, 1783)",NaN,Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34165,5729,Norge,Vepser,Vepser,Animalia/Arthropoda/Insecta/Hymenoptera/Diapri...,116045,Zygota subaptera,"(Thomson, 1859)",NaN,Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34166,4266,Norge,Biller,Biller,Animalia/Arthropoda/Insecta/Coleoptera/Staphyl...,12000,Zyras collaris,"(Paykull, 1800)",NaN,Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34167,6965,Norge,Sopper,Sopper,Fungi/Ascomycota/Sareomycetes/Sareales/Zythiac...,133712,Zythia resinae,(Ehrenb.) P. Karst.,kvaebeger,Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34168,32025,Norge,Sopper,Sopper,Fungi/Ascomycota/Sordariomycetes/Hypocreales/N...,128479,Zythiostroma pinastri,(P. Karst.) Höhn.,NaN,Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34169,29639,Norge,Tovinger,Tovinger,Animalia/Arthropoda/Insecta/Diptera/Chironomid...,17267,Aagaardia sivertseni,"(Aagaard, 1979)",NaN,Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Fremmedartslista

In [93]:
#FA_l = pd.read_csv("https://artsdatabanken.no/Fab2018/api/export/csv")
#FA_l = pd.read_csv("https://artsdatabanken.no/Fab2018/api/export/csv", chunksize=1, header=None, encoding='utf-8')
#url = "https://artsdatabanken.no/Fab2018/api/export/csv"
url = "https://artsdatabanken.no/lister/fremmedartslista/2023?Name=&SortBy=ScientificName&Meta=Visited&IsCheck=Area&IsCheck=dcin&IsCheck=AxBdescription&IsCheck=dcok&IsCheck=AssessedChangedCategory&IsCheck=ClimateAffected&IsCheck=ClimateNotAffected&IsCheck=eds&IsCheck=sal&IsCheck=Insecta&IsCheck=Crustacea&IsCheck=TaxonomicRank&TaxonRank=AssessedAtSameRank&IsCheck=Nta&IsCheck=Ntn&IsCheck=Importation&IsCheck=Introduction&IsCheck=Spread&Export=true"
FA_l = pd.read_excel(url)

In [95]:
#FA_l[FA_l["Fremmedartsstatus"]=="Fremmedart"]
FA_l[FA_l["Fremmedartsstatus"]=='Utenfor avgrensningen']
FA_l = FA_l[~FA_l["Fremmedartsstatus"].isin(['Ikke fremmed'])]
#FA_l
#FA_l['Risikokategori 2018'].unique()

In [101]:
RL.columns

Index(['Id for vurderingen', 'Vurderingsområde', 'Ekspertkomité', 'Artsgruppe',
       'Taksonomisk sti', 'Vitenskapelig navn id', 'Vitenskapelig navn',
       'Autor', 'Populærnavn', 'Taksonomisk nivå',
       'Årstall for siste revisjon', 'Kategori 2021', 'Kriterier 2021',
       'Kriteriedokumentasjon', 'Begrunnelse nedgradering av kategori',
       'Risiko for utdøing sterkt påvirket av populasjoner i naboland',
       'Er arten trolig utdødd', 'Begrunnelse for endring av kategori',
       'Kategori 2015', 'Kriterier 2015', 'Kategori 2010', 'Kriterier 2010',
       'Andel av europeisk populasjon i Norge',
       'Andel av global populasjon i Norge',
       'Nåværende bestand som andel av maks. bestand', 'Hovedhabitat',
       'Påvirkningsfaktorer', 'Østfold', 'Oslo og Akershus', 'Hedmark',
       'Oppland', 'Buskerud', 'Vestfold', 'Telemark', 'Aust-Agder',
       'Vest-Agder', 'Rogaland', 'Hordaland', 'Sogn og Fjordane',
       'Møre og Romsdal', 'Trøndelag', 'Nordland', 'Troms', 'Finnmark',
       'Jan Mayen', 'Nordsjøen', 'Norskehavet',
       'Barentshavet nord og Polhavet', 'Barentshavet sør', 'Grønlandshavet'],
      dtype='object')

In [102]:
# FA bruker en annen inndeling enn RL på Artsgruppe
# Basert på at både RL og FA bruker taksonomisk sti, så kan man bruke den som et oppslagsliste for å mappe verdier fra RL.artsgruppe til FA_l
# Subset RL with unique values of columns "Taksonomisk sti" and "Artsgruppe"
AG = RL[['Taksonomisk sti', 'Artsgruppe']].drop_duplicates()
AG_2 = FA_l[['Taksonomisk sti', 'Artsgruppe']].drop_duplicates()

# Function to find corresponding Artsgruppe in AG/Rødlista based on Taksonomisk sti
def find_artsgruppe(taksonomisk_sti):
    for index, row in AG.iterrows():
        if taksonomisk_sti in row['Taksonomisk sti']:
            return row['Artsgruppe']
    return None

# Add new column "Artsgruppe_2" to FA_l
FA_l['Artsgruppe'] = FA_l['Artsgruppe'].apply(lambda x: find_artsgruppe(x) if pd.notna(x) else None)

In [103]:
#FA_l[FA_l["Taksonomisk sti"].str.contains("Insecta")]
FA_l.loc[FA_l["Taksonomisk sti"].isna(),"Taksonomisk sti"]="-"
FA_l.loc[(FA_l["Artsgruppe"].isna()) & (FA_l["Taksonomisk sti"].str.contains("Insecta")),"Artsgruppe"]="Insekter"
FA_l.loc[(FA_l["Artsgruppe"].isna()) & (FA_l["Taksonomisk sti"].str.contains("Crustacea")),"Artsgruppe"]="Krepsdyr"
FA_l.loc[(FA_l["Artsgruppe"].isna()) & (FA_l["Taksonomisk sti"].str.contains("Molusca")),"Artsgruppe"]="Bløtdyr"
#FA_l.loc[FA_l["Artsgruppe"].isna()]
#FA_l.loc[FA_l["Taksonomisk sti"].str.contains("Insecta"),"Artsgruppe"]#="Insekter"

In [104]:
FA_l["Kriterium_Fremmede_arter"]="X"
FA_l.loc[FA_l["Vurderingsområde"]=="Fastlands-Norge med havområder","Vurderingsområde"]="Norge"# Harmonisere med rødlisten

### ADB statuser

In [105]:
FA = FA_l[['Vitenskapelig navn id','Vitenskapelig navn','Populærnavn','Risikokategori 2023','Vurderingsområde', 'Ekspertkomité', 'Artsgruppe','Kriterium_Fremmede_arter']]
RL = RL[['Vitenskapelig navn id','Vitenskapelig navn','Populærnavn','Kategori 2021','Andel av europeisk populasjon i Norge','Vurderingsområde', 'Ekspertkomité', 'Artsgruppe']]
# Merger på alle kolonner som de har til felles
ADB = FA.merge(RL, on = list(FA_l.columns.intersection(RL.columns)), how = "outer")
#ADB = pd.concat([FA_l[['Vitenskapelig navn id','Vitenskapelig navn','Taksonomisk sti','Populærnavn','Risikokategori 2023','Vurderingsområde', 'Ekspertkomité', 'Artsgruppe','Kriterium_Fremmede_arter']],RL[['Taksonomisk sti','Vitenskapelig navn id','Vitenskapelig navn','Populærnavn','Kategori 2021','Andel av europeisk populasjon i Norge','Vurderingsområde', 'Ekspertkomité', 'Artsgruppe']]])

# Forvaltningsstatus

In [106]:
import pandas as pd
url = "https://geoapi.p.aks.miljodirektoratet.no/forvaltningsstatus_arter/v1/getStatusAsCsv"
forvaltningsstatus =pd.read_csv(url, sep = ",")
display(forvaltningsstatus)

,objectid,vitenskapelig_navn_id,vitenskapelig_navn,norsk_navn,freda,prioritert,spesielle_oekologiske_former,bonn_kategori,bonn_bevaringsstatus,bern_kategori,bern_bevaringsstatus,ospar_kategori,ospar_bevaringsstatus,eea_id,roedliste_statuser
0,1,1590.0,Zootoca vivipara,nordfirfisle,0,0,0,NaN,NaN,Annex III,NaN,NaN,NaN,https://eunis.eea.europa.eu/species/24156,LC/LC - Livskraftig/LC - Livskraftig
1,2,3461.0,Anas platyrhynchos,stokkand,0,0,0,Annex II,NaN,Annex III,NaN,NaN,NaN,https://eunis.eea.europa.eu/species/869,LC/LC - Livskraftig/LC - Livskraftig
2,3,3471.0,Anser anser,grågås,0,0,0,Annex II,NaN,Annex III,NaN,NaN,NaN,https://eunis.eea.europa.eu/species/876,LC/LC - Livskraftig/LC - Livskraftig
3,4,3487.0,Aythya fuligula,toppand,0,0,0,Annex II,NaN,Annex III,NaN,NaN,NaN,https://eunis.eea.europa.eu/species/909,LC/LC - Livskraftig/LC - Livskraftig
4,5,3501.0,Bucephala clangula,kvinand,0,0,0,Annex II,NaN,Annex III,NaN,NaN,NaN,https://eunis.eea.europa.eu/species/923,LC/LC - Livskraftig/LC - Livskraftig
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,438,121126.0,Vertigo (Vertilla) angustior,smalknøttsnegl,0,0,0,NaN,NaN,Annex I (R6),NaN,NaN,NaN,https://eunis.eea.europa.eu/species/367,NT/-/-
438,439,121308.0,Margaritifera (Margaritifera) margaritifera,elvemusling,0,0,0,NaN,NaN,Annex I (R6),NaN,NaN,NaN,https://eunis.eea.europa.eu/species/245,VU/-/-
439,440,170109.0,Mannia triandra,NaN,0,0,0,NaN,NaN,Annex I (R6),NaN,NaN,NaN,https://eunis.eea.europa.eu/species/4273,CR/-/-
440,441,192388.0,Brachythecium novae-angliae,oremose,0,0,0,NaN,NaN,Annex I (R6),NaN,NaN,NaN,https://eunis.eea.europa.eu/species/19877,NT/LC - Livskraftig/-
441,442,214235.0,Campylophyllum montanum,huldrebekkemose,0,0,0,NaN,NaN,Annex I (R6),NaN,NaN,NaN,https://eunis.eea.europa.eu/species/3724,EN/VU - Sårbar/-

In [107]:
forvaltningsstatus["Streng"]=((~forvaltningsstatus["bern_kategori"].fillna("-").str.contains("III")) & (forvaltningsstatus["bern_kategori"].fillna("-").str.contains("I"))) | (forvaltningsstatus[["ospar_kategori", "bonn_kategori"]].apply(lambda x: x.notna().any(), axis = 1))
forvaltningsstatus["Dårlig"] = ((forvaltningsstatus["bern_bevaringsstatus"].notna() & forvaltningsstatus["bonn_bevaringsstatus"].notna() & forvaltningsstatus["ospar_bevaringsstatus"].notna()) | (RL["Andel av europeisk populasjon i Norge"].str.contains("50")) | forvaltningsstatus["roedliste_statuser"].str.contains("EN|CR|VU|DD|NT"))
forvaltningsstatus.loc[forvaltningsstatus["Streng"] & forvaltningsstatus["Dårlig"],"Hensynskrevende"] = "Spesielt"
forvaltningsstatus.loc[forvaltningsstatus["Streng"] & ~forvaltningsstatus["Dårlig"],"Hensynskrevende"] = "Annet"

# Verdsatte arter

In [108]:
import numpy as np
import pandas as pd

In [110]:
ADB = ADB.rename(columns={'Kategori 2021':"RL_status","Vitenskapelig navn id":"vitenskapelig_navn_id","Vitenskapelig navn":"vitenskapelig_navn"})
VitID2 = pd.DataFrame(data = {"vitenskapelig_navn_id":np.concatenate([forvaltningsstatus["vitenskapelig_navn_id"],ADB["vitenskapelig_navn_id"]])})
VitID = pd.DataFrame(data = {"vitenskapelig_navn_id":VitID2["vitenskapelig_navn_id"].unique()})

In [142]:
AV = VitID.merge(right = ADB, how = "left", on ="vitenskapelig_navn_id")
AV = AV.merge(right = forvaltningsstatus.drop(columns=['vitenskapelig_navn']), how = "left", on = ["vitenskapelig_navn_id"])

In [144]:
# Hardkoder at artene i spesielle økologiske former er fugler
AV.loc[AV["spesielle_oekologiske_former"]==1,"Artsgruppe"]="Fugler"
# Tilsvarende for prioriterte arter
AV.loc[AV["vitenskapelig_navn_id"]==3768,"Artsgruppe"]="Fugler"
AV[(AV["prioritert"]==1)]
# Og fikser deres norske navn
AV.loc[(AV["Populærnavn"].isna()) & (~AV["norsk_navn"].isna()), "Populærnavn"] = AV["norsk_navn"]

In [145]:
AV.loc[AV["vitenskapelig_navn_id"]==3768]

,vitenskapelig_navn_id,vitenskapelig_navn,Populærnavn,Risikokategori 2023,Vurderingsområde,Ekspertkomité,Artsgruppe,Kriterium_Fremmede_arter,RL_status,Andel av europeisk populasjon i Norge,...,bonn_bevaringsstatus,bern_kategori,bern_bevaringsstatus,ospar_kategori,ospar_bevaringsstatus,eea_id,roedliste_statuser,Streng,Dårlig,Hensynskrevende
164,3768.0,NaN,"svarthalespove, underart islandica",NaN,NaN,NaN,Fugler,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN

In [146]:
# "Øvrige dyr"
AV.loc[AV["Artsgruppe"].isna(), "Artsgruppe"]  = "Øvrige dyr"

In [160]:
# Function to map values
# Make sure that the prioritized values occur first, so that lower values are not used when a species can have several
def map_values(row):
    #print(row)
    #if row['freda'] == 1 or row['prioritert'] == 1:
        #return 'Svært stor verdi'
    if (row['RL_status'] in ['CR', 'EN']) or (row['freda'] == 1 or row['prioritert'] == 1):
        return 'Svært stor verdi'
    elif (row['RL_status'] == 'VU') or (row["Hensynskrevende"]=="Spesielt"):
        return 'Stor verdi'
    elif row['RL_status'] in ['NT', 'DD']:
        return 'Middels verdi'
    elif (row['RL_status'] == 'LC') or (row["Hensynskrevende"]=="Annet"):
        return 'Noe verdi'    
    else:
        return "-"

# Apply the function to the DataFrame
AV['Forvaltningsverdi'] = AV.apply(map_values, axis=1)

In [159]:
AV[AV['prioritert']==1][["vitenskapelig_navn","Populærnavn","RL_status","prioritert","Forvaltningsverdi"]]

,vitenskapelig_navn,Populærnavn,RL_status,prioritert,Forvaltningsverdi
164,NaN,"svarthalespove, underart islandica",NaN,1.0,Svært stor verdi
171,Cicindela maritima,elvesandjeger,EN,1.0,Svært stor verdi
172,Scolitantides orion,klippeblåvinge,CR,1.0,Svært stor verdi
174,Heterodermia speciosa,elfenbenslav,EN,1.0,Svært stor verdi
175,Zostera noltei,dvergålegras,EN,1.0,Svært stor verdi
178,Cephalanthera rubra,rød skogfrue,EN,1.0,Svært stor verdi
182,Herminium monorchis,honningblom,CR,1.0,Svært stor verdi
183,Nigritella nigra,svartkurle,EN,1.0,Svært stor verdi
194,Oxytropis campestris subsp. scotica,skredmjelt,CR,1.0,Svært stor verdi
205,Sphagnum (Cuspidata) troendelagicum,trøndertorvmose,EN,1.0,Svært stor verdi
376,Dracocephalum ruyschiana,dragehode,VU,1.0,Svært stor verdi
390,Anser erythropus,dverggås,CR,1.0,Svært stor verdi
413,Osmoderma eremita,eremitt,CR,1.0,Svært stor verdi
414,Vulpes lagopus,fjellrev,EN,1.0,Svært stor verdi
415,Vulpes lagopus,fjellrev,LC,1.0,Svært stor verdi

In [161]:
# Function to set criteria based on RL_status
def set_criteria(row):
    if row['RL_status'] == 'NT':
        row['Kriterium_NT'] = 'X'
    elif row['RL_status'] == 'DD':
        row['Kriterium_DD'] = 'X'
    elif row['RL_status'] == 'VU':
        row['Kriterium_sårbar art'] = 'X'
    elif row['RL_status'] == 'CR':
        row['Kriterium_kritisk trua art'] = 'X'
    elif row['RL_status'] == 'EN':
        row['Kriterium_sterkt trua art'] = 'X'
    elif row["Hensynskrevende"]=="Spesielt":
        row['Kriterium_Andre spesielt_hensynskrevende_arter']='X'
    elif row["Hensynskrevende"]=="Annet":
        row['Kriterium_Hensynskrevende_arter']='X'        
    return row

# Apply the function to each row
AV = AV.apply(set_criteria, axis=1)

In [162]:
AV = AV.rename(columns={"RL_status":"Rødlistestatus",'prioritert':'Kriterium_Prioriterte_arter','freda':"Kriterium_Fredete_arter","spesielle_oekologiske_former":"Kriterium_Spesielle_okologiske_former"})

In [165]:
# for arter som ikke har noen vurdering, slik som priorirterte (under)arter
AV.loc[AV["Vurderingsområde"].isna(),"Vurderingsområde"]="Norge" 
# Identifisere ansvarsarter
AV.loc[AV["Andel av europeisk populasjon i Norge"].isna(),"Andel av europeisk populasjon i Norge"]="-"
AV.loc[AV["Andel av europeisk populasjon i Norge"].str.contains("50"), "Kriterium_Ansvarsart"] = "1"
# Remove potential 0's,
# replace potential X's with 1's
AV.loc[:, AV.columns.str.startswith('Kriterium_')] = AV.loc[:, AV.columns.str.startswith('Kriterium_')].replace({0: np.nan, 'X': 1})

In [167]:
# Snake_case it all
AV.columns = (AV.columns
                .str.replace(' ', '_', regex=True)
                .str.lower()
             )
AV.columns

Index(['andel_av_europeisk_populasjon_i_norge', 'artsgruppe', 'dårlig',
       'ekspertkomité', 'forvaltningsverdi', 'hensynskrevende',
       'kriterium_andre_spesielt_hensynskrevende_arter', 'kriterium_dd',
       'kriterium_fremmede_arter', 'kriterium_hensynskrevende_arter',
       'kriterium_nt', 'kriterium_kritisk_trua_art',
       'kriterium_sterkt_trua_art', 'kriterium_sårbar_art', 'populærnavn',
       'rødlistestatus', 'risikokategori_2023', 'streng', 'vurderingsområde',
       'bern_bevaringsstatus', 'bern_kategori', 'bonn_bevaringsstatus',
       'bonn_kategori', 'eea_id', 'kriterium_fredete_arter', 'norsk_navn',
       'objectid', 'ospar_bevaringsstatus', 'ospar_kategori',
       'kriterium_prioriterte_arter', 'roedliste_statuser',
       'kriterium_spesielle_okologiske_former', 'vitenskapelig_navn',
       'vitenskapelig_navn_id', 'kriterium_ansvarsart'],
      dtype='object')

In [168]:
#AV[AV['populærnavn']=="bendelløk"]
AV[AV["kriterium_prioriterte_arter"]==1]

,andel_av_europeisk_populasjon_i_norge,artsgruppe,dårlig,ekspertkomité,forvaltningsverdi,hensynskrevende,kriterium_andre_spesielt_hensynskrevende_arter,kriterium_dd,kriterium_fremmede_arter,kriterium_hensynskrevende_arter,...,norsk_navn,objectid,ospar_bevaringsstatus,ospar_kategori,kriterium_prioriterte_arter,roedliste_statuser,kriterium_spesielle_okologiske_former,vitenskapelig_navn,vitenskapelig_navn_id,kriterium_ansvarsart
164,-,Fugler,False,NaN,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,"svarthalespove, underart islandica",152.0,NaN,NaN,1.0,NaN,NaN,NaN,3768.0,NaN
171,5 - 25 %,Biller,False,Biller,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,elvesandjeger,159.0,NaN,NaN,1.0,NaN,NaN,Cicindela maritima,5326.0,NaN
172,< 1 %,Sommerfugler,False,Sommerfugler,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,klippeblåvinge,160.0,NaN,NaN,1.0,NaN,NaN,Scolitantides orion,46568.0,NaN
174,25 - 50 %,Laver,False,Laver,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,elfenbenslav,162.0,NaN,NaN,1.0,NaN,NaN,Heterodermia speciosa,73657.0,1
175,< 1 %,Karplanter,False,Karplanter,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,dvergålegras,163.0,NaN,NaN,1.0,NaN,NaN,Zostera noltei,99390.0,NaN
178,< 1 %,Karplanter,False,Karplanter,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,rød skogfrue,166.0,NaN,NaN,1.0,NaN,NaN,Cephalanthera rubra,99485.0,NaN
182,< 1 %,Karplanter,False,Karplanter,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,honningblom,170.0,NaN,NaN,1.0,NaN,NaN,Herminium monorchis,99524.0,NaN
183,> 50 %,Karplanter,False,Karplanter,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,svartkurle,171.0,NaN,NaN,1.0,NaN,NaN,Nigritella nigra,99537.0,1
194,1 - 5 %,Karplanter,False,Karplanter,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,skredmjelt,182.0,NaN,NaN,1.0,NaN,NaN,Oxytropis campestris subsp. scotica,102019.0,NaN
205,> 50 %,Moser,False,Moser,Svært stor verdi,NaN,NaN,NaN,NaN,NaN,...,trøndertorvmose,192.0,NaN,NaN,1.0,NaN,NaN,Sphagnum (Cuspidata) troendelagicum,105030.0,1
376,5 - 25 %,Karplanter,True,Karplanter,Svært stor verdi,Spesielt,NaN,NaN,NaN,NaN,...,dragehode,339.0,NaN,NaN,1.0,VU/LC - Livskraftig/-,NaN,Dracocephalum ruyschiana,102285.0,NaN
390,> 50 %,Fugler,True,Fugler,Svært stor verdi,Spesielt,NaN,NaN,NaN,NaN,...,dverggås,352.0,NaN,NaN,1.0,CR/EN - Sterkt truet/VU - Sårbar,NaN,Anser erythropus,3478.0,1
413,< 1 %,Biller,True,Biller,Svært stor verdi,Spesielt,NaN,NaN,NaN,NaN,...,eremitt,373.0,NaN,NaN,1.0,CR/NT - Nær truet/NT - Nær truet,NaN,Osmoderma eremita,10696.0,NaN
414,1 - 5 %,Pattedyr,True,Pattedyr,Svært stor verdi,Spesielt,NaN,NaN,NaN,NaN,...,fjellrev,374.0,NaN,NaN,1.0,EN/LC - Livskraftig/LC - Livskraftig,NaN,Vulpes lagopus,48032.0,NaN
415,Helt ukjent,Pattedyr,True,Pattedyr,Svært stor verdi,Spesielt,1.0,NaN,NaN,NaN,...,fjellrev,374.0,NaN,NaN,1.0,EN/LC - Livskraftig/LC - Livskraftig,NaN,Vulpes lagopus,48032.0,NaN

# Arter av nasjonal forvaltningsinteresse

In [172]:
AV.columns

Index(['andel_av_europeisk_populasjon_i_norge', 'artsgruppe', 'dårlig',
       'ekspertkomité', 'forvaltningsverdi', 'hensynskrevende',
       'kriterium_andre_spesielt_hensynskrevende_arter', 'kriterium_dd',
       'kriterium_fremmede_arter', 'kriterium_hensynskrevende_arter',
       'kriterium_nt', 'kriterium_kritisk_trua_art',
       'kriterium_sterkt_trua_art', 'kriterium_sårbar_art', 'populærnavn',
       'rødlistestatus', 'risikokategori_2023', 'streng', 'vurderingsområde',
       'bern_bevaringsstatus', 'bern_kategori', 'bonn_bevaringsstatus',
       'bonn_kategori', 'eea_id', 'kriterium_fredete_arter', 'norsk_navn',
       'objectid', 'ospar_bevaringsstatus', 'ospar_kategori',
       'kriterium_prioriterte_arter', 'roedliste_statuser',
       'kriterium_spesielle_okologiske_former', 'vitenskapelig_navn',
       'vitenskapelig_navn_id', 'kriterium_ansvarsart'],
      dtype='object')

In [173]:
ANF = AV.loc[(AV["rødlistestatus"].isin(["NT", "DD", "VU", "CR", "EN"])) | (~AV["hensynskrevende"].isna()) | (AV["kriterium_ansvarsart"]=="X")
             | (AV["risikokategori_2023"].isin(['SE', 'HI'])) | (AV["forvaltningsverdi"].isin(["Svært stor verdi", "Stor verdi", "Middels verdi"]))]
ANF = ANF.loc[ANF["vurderingsområde"].str.contains("Norge")] #Begrenser til fastlandsnorge

ANF = ANF[["vitenskapelig_navn_id", "artsgruppe", "vitenskapelig_navn", "populærnavn", "rødlistestatus","forvaltningsverdi", "kriterium_prioriterte_arter", "kriterium_fredete_arter", "kriterium_kritisk_trua_art", "kriterium_sterkt_trua_art", "kriterium_sårbar_art",	"kriterium_andre_spesielt_hensynskrevende_arter", "kriterium_spesielle_okologiske_former", "kriterium_nt", "kriterium_dd", "kriterium_hensynskrevende_arter","kriterium_ansvarsart","kriterium_fremmede_arter"]]
ANF.columns = ANF.columns.str.replace(" ","_")
ANF.columns = ANF.columns.str.lower()
ANF.columns = ANF.columns.str.replace("æ","ae")
ANF.columns = ANF.columns.str.replace("ø","oe")
ANF.columns = ANF.columns.str.replace("å","aa")

In [174]:
ANF = ANF.sort_values("vitenskapelig_navn_id")
ANF = ANF.drop_duplicates()

In [176]:
# Export
ANF.to_csv('C:/data/ANF3.csv', index=False)
ANF.to_excel("C:/data/output.xlsx", index = False)